name: Build members from Google Sheets
permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - scripts/build.py
      - .github/workflows/build.yml
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas segno

      - name: Generate member pages
        env:
          CSV_URL: ${{ secrets.CSV_URL }}
          MEMBERS_CODE: ${{ secrets.MEMBERS_CODE }}   # ton secret code (anglais)
          # SHEET_LINK: ${{ secrets.SHEET_LINK }}     # optionnel si tu le crées
        run: python scripts/build.py

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update members from Google Sheets"
          branch: main
